{
 "title": "Network Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   {
    "name": "Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "DC Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "interface_traffic_rate_in_bps", "legendFormat": "__auto" },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 23, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "interface_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": " Interface Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_received_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_paths{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Paths"
    }
   ]
  },
  {
   "title": "BGP Peer Stats",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_disabled_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "Bridge Stats (All Tables)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(network_instance_bridge_table_statistics_active_entries{source=\"$NE\"})",
     "legendFormat": "Active Entries"
    },
    {
     "expr": "sum(network_instance_bridge_table_statistics_total_entries{source=\"$NE\"})",
     "legendFormat": "Total Entries"
    },
    {
     "expr": "sum(network_instance_bridge_table_statistics_failed_entries{source=\"$NE\"})",
     "legendFormat": "Failed Entries"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$NE\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "platform_control_memory_free{source=\"$NE\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$NE\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "platform_control_memory_reserved{source=\"$NE\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "platform_control_memory_physical{source=\"$NE\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 29 },
   "targets": [
    {
     "expr": "system_app_management_application_pid{source='$NE'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Logging $NE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log: $Logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 15, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "{application=\"$Logs\", source=\"$NE\"}"
      }
     ]
    },
    {
     "title": "Total logs $NE",
     "type": "piechart",
     "gridPos": { "h": 21, "w": 9, "x": 15, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (application) (count_over_time({source=\"$NE\"}[$__range]))",
       "legendFormat": "{{application}}"
      }
     ]
    },
    {
     "title": "Log volume: $Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum by (level) (count_over_time({application=\"$Logs\",source=\"$NE\"} | logfmt [$__interval]))",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  }
 ]
}